version: '3'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - wildfly-server

  wildfly-server:
    build:
      context: .
      dockerfile: Dockerfile-wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - mysql-server
    environment:
      - MYSQL_HOST=regterscdb.cxviwqvwghdq.eu-central-1.rds.amazonaws.com
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=regtertestdata
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=BroodjeKaas
      - CORS_ENABLED=false
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS # Voeg de toegestane methoden toe
      - CORS_ALLOWED_HEADERS=CSRF-Token, X-Requested-By, Authorization, Content-Type # Voeg de toegestane headers toe

  mysql-server:
    image: mysql:latest
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=casper2005!  # Set your desired root password here
